/*
 * This source file was generated by the Gradle 'init' task
 */
package taller5;

import java.text.DecimalFormat;
public class App {
    
    public static void main(String[] args) {
        
        try {
            
            System.out.println(aleatorio(3000));
            System.out.println(Simular_ventas());
            System.out.println(Calcular_empaque(2000));
            System.out.println(Jugar_21(5));
            
            
        } 
        
        catch (Exception e) {
            // TODO: handle exception
        }
    }


    /*
    
        1.	Desarrolle un algoritmo e impleméntelo en Java que: le pida al usuario un número entero positivo 
        entre 1000 y 9999. En un ciclo genere números de manera aleatoria y cuente los intentos que hizo antes 
        de hallar el número exactamente.
        
    
    */ 
    public static String aleatorio(int a){
        try {
            String mensaje = "";
            int aleatorio = 0, repeticiones = 0;
            if (a < 1000 || a > 9999) {
                System.out.println("El número debe estar entre 1000 y 9999.");
            }
            do {
                aleatorio = (int)(Math.random()*(9999-1000))+ 1000;
                repeticiones++;
            } while (aleatorio != a);

            mensaje = "el numero de intentos para encontrar a " + a + " fue de: " + repeticiones;
            return mensaje;
        } catch (Exception e) {
            return "error";
        }
    }




    /* 
     
        2.	Se requiere una función en java que simule las ventas de tres años para un almacén. Para cada año, deberá generar 
        un aleatorio para cada mes hasta completar los 12 meses. La función se llamará Simular_ventas, y debe retornar un String 
        al final que muestre las ventas de cada año, así:
        
            Año 1
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###
            Total ventas Año 1:  $##.###.###
            
            Año 2
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###
            Total ventas Año 2: $##.###.###
            
            Año 3
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###

            Total ventas Año 3: $##.###.###
            
            Investigue sobre la clase DecimalFormat para mostrar bien la salida. 
            import java.text.DecimalFormat;
            DecimalFormat form_pesos = new DecimalFormat("$#,###.00");
      
    */


    public static String Simular_ventas(){
        try {
            String  mensaje = "";
            final int an = 3, meses = 12, max = 10000000;
            int aleatorio = 0, total_an = 0;
            DecimalFormat form_pesos = new DecimalFormat("$#,###,###.00");

            for(int i = 1; i <= an; i++){
                System.out.println("\naño " + i +"\n");
                total_an = 0;
                
            for(int a = 1; a <= meses; a++) {
                aleatorio = (int)(Math.random()*(max));
                System.out.println(" ventas mes " + a + ":" + form_pesos.format(aleatorio) + "\n");
                
                total_an += aleatorio;
                
              }
              
              System.out.println(" el total de ventas del año "+ i + " es de " + total_an);

             



            }
            
            return mensaje;
        } catch (Exception e) {
            
            return "error";
        }
    }

    



    /*  
     
        3.	En una fábrica se tiene el siguiente patrón de empaque: En una estiba(o pallet) caben 16  cajas y en cada caja, 
        caben 30 bombillas. Desarrolle una función que se llame: Calcular_empaque que: reciba como argumento la cantidad de 
        bombillas que se deben empacar y a partir de allí: calcule cuántas cajas necesita, cuántas estibas o pallets necesita. 
        Luego escriba lo siguiente: 

        Para ### bombillas, se necesitan ## cajas y ## pallets. Se quedan ### bombillas sin empacar. Se empacará así:

        Pallet 1 --> Caja1, Caja2……,Caja16
        Pallet2 -->  Caja17, Caja18…..Caja 32
        .
        Pallet n -- > Caja m, caja m+1…..
        
        La función retornará un texto, con la información anterior. Pruebe la función llamándola desde el programa principal: solicite al usuario el número de bombillas e invoque la función para imprimir en el main, los resultados.



    */
    public static String Calcular_empaque(int bombillas) {
        try {
            final int bombillasPorCaja = 30;
            final int cajasPorPallet = 16;
            int sobrante = 0, i = 0, contador = 1;
            String mensaje = "";
            
            int totalCajas = (int) Math.ceil((double) bombillas / bombillasPorCaja);
            
            int totalPallets = (int) Math.ceil((double) totalCajas / cajasPorPallet);
            
            int bombillasEmpacadas = totalCajas * bombillasPorCaja;
            int bombillasNoEmpacadas = bombillasEmpacadas - bombillas;
            System.out.println( "Para "+ bombillas +" bombillas, se necesitan "+ totalCajas +" cajas y " +totalPallets+ " pallets. Se quedan " +bombillasNoEmpacadas +" bombillas sin empacar. Se empacará así:");

                for( i = 1; i <= totalPallets  ; i++){
                    mensaje += "\n\nPallet "+  i  +"--> ";
                    
                    
                        

                    
                    for(int a = 1; a <= cajasPorPallet && contador <= totalCajas ; a++ ){
                       
                        mensaje += "caja " + contador + " , ";
                        contador++;
                        if(a == cajasPorPallet - 1 && contador <= totalCajas){
                            
                            
                    
                    }
                        }
                        
                        


                }

                
            return mensaje;
        } catch (Exception e) {
            return "error";
        }
    }



    

    /* 
    

        4.	En un juego, cada jugador tiene 3 intentos para sacar cartas de una baraja. Las cartas van numeradas entre 1 y 10. 
        Una función Jugar_21, deberá simular el juego para una cantidad de usuarios que enviará el usuario desde el main entre 1 y 6.

        Para cada uno de los jugadores, el programa le calculará 3 cartas al azar y al final imprimirá el juego para cada jugador basado en las siguientes reglas: 
        
        Si saca 21 exactos: juego perfecto
        Si saca más de 21: se pasó
        Si saca menos de 21: faltaron puntos

        La función deberá imprimir los puntos de cada jugador junto con la regla anterior, como muestra el ejemplo:

        Jugador X, puntos 21 -- > juego perfecto
        Jugador Y, puntos 26 -- > se pasó
        .
        .


    */
    public static String Jugar_21(int jugadores){
        try {
            String mensaje = "";
            final byte juego = 21, nro_cartas = 3, lim_sup = 10, lim_inf = 1, jugadores_max = 6;
            int aleatorio = 0;

            if(jugadores < lim_inf || jugadores > jugadores_max){
            System.out.println("cantidad de jugadores invalida");
            }
            else{
            for (int i = 1; i <= jugadores; i++) {
                int puntos = 0; // Puntaje del jugador
             
                // Sumar el valor de las cartas del jugador
                for (int cartas = 1; cartas <= nro_cartas; cartas++) {
                     aleatorio = (int)(Math.random()*(lim_sup) + lim_inf);
                    puntos += aleatorio;
                }
                
                if (puntos == juego) {
                    mensaje += "Jugador " +i+ ", puntos " + puntos +" -- > juego perfecto\n" ;
                    
                } else if (puntos > juego) {
                    mensaje += "Jugador " +i+ ", puntos " + puntos +" -- > se paso\n" ;
                    
                } else {
                    mensaje += "Jugador " +i+ ", puntos " + puntos +" -- > faltaron puntos\n" ;
                    
                }
                

            }
        }
        
            return mensaje;
        } catch (Exception e) {
            return "error";
        }
    }



}




}
